builds:
  - binary: ec2-vuls-config
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
    - README.ja.md
release:
  github:
    owner: ohsawa0515
    name: ec2-vuls-config